language: php
php:
  - 7.4.6
install:
  # - composer install
  - composer install --prefer-dist --optimize-autoloader --quiet
cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate --env testing

script:
  - vendor/bin/phpunit